# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: (WIP) Alex Elliott's Portfolio # This is what shows up in the tab of the browser


# Hero Section
name: Alex Elliott
headline: Electrical Engineering BS + MS Graduate of Cal Poly SLO
description: >- # dont remove this line. this will ignore all new lines until the next section
  Electrical Engineering graduate with 4+ years of experience with Audio-Visual systems and career interests including Control Systems, Signal Processing, Embedded Systems, and Audio Electronics.
  Hobbies and personal interests include DIY Light-Show Design, Modular Synthesizers, and Electronic Music Production & DJing.
  Please note that this page is work-in-progress and as such it may not include all projects I have been working on.
  

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jfif


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: /assets/resume/ElliottAResume11122025_ALLCOURSEWORK.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: alexgelliott    # https://www.linkedin.com/in/{your url slug} 
  github: alexanduhhi    # https://github.com/{your url slug} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instagram: alexanduhhi      # https://instagram.com/{your url slug} 
  youtube:  alexslight-shows         # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Software
    tools:
    - Arduino IDE
    - STM32Cube IDE
    - Schneider Electric Control Expert (PLC/PAC)
    - Schneider Electric Vijeo Designer (HMI)
    - Keysight ADS (RF/EM Design & Simulation)
    - LTSpice (Circuit Sim)
    - Xilinx Vivado (FPGA & Digital Design)
    - KiCad (PCB Design)
    - PrusaSlicer (3D Printing)
    - MATLAB/Simulink (Simulation & Modeling)
    - Linux OS
    - OpenLane VLSI Toolchain
    - Microsoft Word
    - Microsoft Excel
  - category: Prototyping
    tools:
    - 3D Printing
    - PCB Design
    - Circuit Simulation (SPICE)
    - Breadboarding
    - Soldering (THT & SMT)
    - Verification (Using Lab Equipment)
  - category: Lab Equipment
    tools:
    - Oscilloscopes & DSOs
    - Power Supplies
    - Multimeters
    - Function Generators
    - Vector Network Analyzers (VNAs)
    - Spectrum Analyzers
  - category: Programming Languages
    tools:
    - C/C++
    - PLC/PAC (LD, FBD, ST)
    - Verilog/System-Verilog
    - MATLAB (Scripting Languages)
    - SPICE
  - category: Development Boards & MCUs
    tools:
    - Arduino Uno R3
    - Arduino Mega 2560
    - NodeMCU ESP8266
    - NodeMCU ESP32-WROOM
    - WT32-ETH01
    - Digilent Basys 3 Artix-7 (FPGA)
    - STM32F746NG-DISCO
    - STM32L4A6ZG-NUCLEO
  - category: Soft Skills
    tools:
    - Client Communication
    - Professional Email Etiquette
    - Documentation & Technical Writing
  - category: Audio-Visual
    tools:
    - ETC Eos & Nomad
    - Obsidian Onyx
    - DMXcat
    - Vixen Lights
    - Falcon Pi Player (FPP)
    - Allen&Heath Avantis
    - Allen&Heath MixWizard
    - Yamaha QL-5
    - Ableton Live
    - FL Studio
    - Traktor Pro 3/4
    - Christie Projectors


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   mananqjy



# Active theme (Update this to switch themes). Make sure to keep the indentation the same.
colors: # this is the MINT theme
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
